fragment RoleFragment on Role {
  id
  title
}

mutation CreateRole($input: RoleInput!) {
  createRole(input: $input) {
    ...RoleFragment
  }
}

query ReadRoles {
  roles {
    ...RoleFragment
  }
}

mutation UpdateRole($id: ID!, $input: RoleInput!) {
  updateRole(id: $id, input: $input) {
    ...RoleFragment
  }
}

mutation DestroyRole($id: ID!) {
  destroyRole(id: $id) {
    ...RoleFragment
  }
}