#import './fragment.gql'

mutation CreateTeam($input: TeamInput!) {
  createTeam(input: $input) {
    ...TeamFragment
  }
}

query ReadTeams {
  teams {
    ...TeamFragment
  }
}

mutation UpdateTeam($id: ID!, $input: TeamInput!) {
  updateTeam(id: $id, input: $input) {
    ...TeamFragment
  }
}

mutation DestroyTeam($id: ID!) {
  destroyTeam(id: $id) {
    ...TeamFragment
  }
}