fragment ToolFragment on Tool {
  id
  title
}

mutation CreateTool($input: ToolInput!) {
  createTool(input: $input) {
    ...ToolFragment
  }
}

query ReadTools {
  tools {
    ...ToolFragment
  }
}

mutation UpdateTool($id: ID!, $input: ToolInput!) {
  updateTool(id: $id, input: $input) {
    ...ToolFragment
  }
}

mutation DestroyTool($id: ID!) {
  destroyTool(id: $id) {
    ...ToolFragment
  }
}