mutation CreateTool($input: ToolInput!) {
  createTool(input: $input) {
    id
    title
  }
}

query ReadTools {
  tools {
    id
    title
  }
}

mutation UpdateTool($id: ID!, $input: ToolInput!) {
  updateTool(id: $id, input: $input) {
    id
    title
  }
}

mutation DestroyTool($id: ID!) {
  destroyTool(id: $id) {
    id
    title
  }
}